export 
{
    getSmurfs,
    postSmurfs,
    FETCH_SMURF_START,
    FETCH_SMURF_SUCCESS,
    FETCH_SMURF_FAIL,
    POST_SMURF_START,
    POST_SMURF_SUCCESS,
    POST_SMURF_FAIL,
    PUT_SMURF_START,
    PUT_SMURF_SUCCESS,
    PUT_SMURF_FAIL,
    DELETE_SMURF_START,
    DELETE_SMURF_SUCCESS,
    DELETE_SMURF_FAIL
} from './smurfActions'